server:
  port: 11050

spring:
  redis:
    matching:
      host: k8e103.p.ssafy.io
      port: 6380
      password: paymong103.!

battle:
  max_distance: 300
  max_search: 10
  max_turn: 10
  default_health: 500
