package com.paymong.common.code

enum class LandingCode {
    LOADING,
    INSTALL, NOT_INSTALL, VALID,
    LOGIN,

    LOGIN_SUCCESS, LOGIN_FAIL,
    REGIST_WEARABLE_SUCCESS,
    HAS_WEARABLE_SUCCESS, HAS_WEARABLE_FAIL
}