package com.paymong.common.code

enum class SoundCode {
    MAIN_BUTTON,
    FEED_BUTTON,
    TRAINING_BUTTON,
    TRAINING_WIN,
    TRAINING_LOSE,
    WALKING_BUTTON,
    BATTLE_BUTTON,
    BATTLE_WIN,
    BATTLE_LOSE,
    BATTLE_ATTACK,
    BATTLE_DEFENCE,
    BATTLE_FIND_SOUND,
    COIN_SOUND,

}
